-- Seed file for Tambay Games
-- Run: supabase db seed
-- Individual game seeds are appended below by game agents

-- ============================================================
-- Pinoy Henyo
-- ============================================================

truncate table henyo_words restart identity cascade;

-- =============================================================
-- pagkain (Food)
-- =============================================================
INSERT INTO henyo_words (word, category) VALUES
  ('Adobo', 'pagkain'),
  ('Sinigang', 'pagkain'),
  ('Lechon', 'pagkain'),
  ('Balut', 'pagkain'),
  ('Halo-Halo', 'pagkain'),
  ('Pancit', 'pagkain'),
  ('Kare-Kare', 'pagkain'),
  ('Dinuguan', 'pagkain'),
  ('Lumpia', 'pagkain'),
  ('Bibingka', 'pagkain'),
  ('Tapsilog', 'pagkain'),
  ('Sisig', 'pagkain'),
  ('Buko Pandan', 'pagkain'),
  ('Champorado', 'pagkain'),
  ('Kwek-Kwek', 'pagkain'),
  ('Tinola', 'pagkain'),
  ('Arroz Caldo', 'pagkain'),
  ('Bulalo', 'pagkain'),
  ('Menudo', 'pagkain'),
  ('Caldereta', 'pagkain'),
  ('Crispy Pata', 'pagkain'),
  ('Taho', 'pagkain'),
  ('Palitaw', 'pagkain'),
  ('Puto', 'pagkain'),
  ('Biko', 'pagkain'),
  ('Mami', 'pagkain'),
  ('Lomi', 'pagkain'),
  ('Kuchinta', 'pagkain'),
  ('Leche Flan', 'pagkain'),
  ('Bangus', 'pagkain'),
  ('Tortang Talong', 'pagkain'),
  ('Ginisang Ampalaya', 'pagkain'),
  ('Inasal', 'pagkain'),
  ('Sinuglaw', 'pagkain'),
  ('Puto Bumbong', 'pagkain'),
  ('Ensaymada', 'pagkain'),
  ('Pandesal', 'pagkain'),
  ('Turon', 'pagkain'),
  ('Ginataan', 'pagkain'),
  ('Ube Halaya', 'pagkain'),
  ('Goto', 'pagkain'),
  ('Spaghetti', 'pagkain'),
  ('Carbonara', 'pagkain'),
  ('Lasagna', 'pagkain'),
  ('Pizza', 'pagkain'),
  ('Isaw', 'pagkain');

-- =============================================================
-- tao (Person)
-- =============================================================
INSERT INTO henyo_words (word, category) VALUES
  ('Jose Rizal',         'tao'),
  ('Coco Martin',        'tao'),
  ('Manny Pacquiao',     'tao'),
  ('Sarah Geronimo',     'tao'),
  ('Ninoy Aquino',       'tao'),
  ('Vice Ganda',         'tao'),
  ('Lea Salonga',        'tao'),
  ('Lapu-Lapu',          'tao'),
  ('Kim Chiu',           'tao'),
  ('Efren Reyes',        'tao'),
  ('Kathryn Bernardo',   'tao'),
  ('Andres Bonifacio',   'tao'),
  ('Cory Aquino',        'tao'),
  ('Bamboo',             'tao'),
  ('Daniel Padilla',     'tao'),
  ('Rodrigo Duterte',    'tao'),
  ('Imelda Marcos',      'tao'),
  ('Fernando Poe Jr',    'tao'),
  ('Charice Pempengco',  'tao'),
  ('Regine Velasquez',   'tao'),
  ('Gary Valenciano',    'tao'),
  ('Dolphy',             'tao'),
  ('Nora Aunor',         'tao'),
  ('Aga Muhlach',        'tao'),
  ('Anne Curtis',        'tao'),
  ('Alden Richards',     'tao'),
  ('Maine Mendoza',      'tao'),
  ('Sandara Park',       'tao'),
  ('Liza Soberano',      'tao'),
  ('Enrique Gil',        'tao'),
  ('Piolo Pascual',      'tao'),
  ('Sharon Cuneta',      'tao'),
  ('Emilio Aguinaldo',   'tao'),
  ('BINI',               'tao'),
  ('SB19',               'tao'),
  ('Lani Misalucha',     'tao'),
  ('Freddie Aguilar',    'tao'),
  ('Ramon Magsaysay',    'tao'),
  ('Donald Trump',    'tao'),
  ('Harry Styles',    'tao'),
  ('Zayn Malik',    'tao'),
  ('Justin Bieber',    'tao'),
  ('Taylor Swift',    'tao'),
  ('Gerald Anderson',    'tao'),
  ('Selena Gomez',    'tao'),
  ('Kim Jong Un',    'tao'),
  ('Alex Eala',    'tao'),
  ('Michael Jackson',    'tao'),
  ('Kobe Bryant',    'tao'),
  ('Lebron James',    'tao'),
  ('Bol Bol',    'tao'),
  ('Stephen Curry',    'tao'),
  ('Tiger Woods',    'tao'),
  ('Michael Phelps',    'tao'),
  ('Barack Obama',    'tao'),
  ('John Wick',    'tao'),
  ('One Direction',    'tao'),
  ('Leonardo Da Vinci',    'tao'),
  ('Leonardo Dicaprio',    'tao'),
  ('Megan Fox',    'tao'),
  ('Jennifer Aniston',    'tao'),
  ('Jennifer Lawrence',    'tao'),
  ('Jennifer Lawrence',    'tao'),
  ('Christiano Ronaldo',    'tao'),
  ('Lionel Messi',    'tao'),
  ('The Rock',    'tao'),
  ('Billie Eilish',    'tao');

-- =============================================================
-- hayop (Animal)
-- =============================================================
INSERT INTO henyo_words (word, category) VALUES
  ('Kalabaw',       'hayop'),
  ('Maya',          'hayop'),
  ('Tarsier',       'hayop'),
  ('Pawikan',       'hayop'),
  ('Agila',         'hayop'),
  ('Daga',          'hayop'),
  ('Baboy-Damo',    'hayop'),
  ('Butanding',     'hayop'),
  ('Kabayo',        'hayop'),
  ('Lobo',          'hayop'),
  ('Pusa',          'hayop'),
  ('Aso',           'hayop'),
  ('Balyena',       'hayop'),
  ('Itik',          'hayop'),
  ('Manok',         'hayop'),
  ('Kambing',       'hayop'),
  ('Baka',          'hayop'),
  ('Baboy',         'hayop'),
  ('Kuneho',        'hayop'),
  ('Palaka',        'hayop'),
  ('Ahas',          'hayop'),
  ('Bayawak',       'hayop'),
  ('Tamaraw',       'hayop'),
  ('Kalapati',      'hayop'),
  ('Uwak',          'hayop'),
  ('Dolphin',        'hayop'),
  ('Pating',        'hayop'),
  ('Pugad',         'hayop'),
  ('Elepante',      'hayop'),
  ('Leon',          'hayop'),
  ('Tigre',         'hayop'),
  ('Unggoy',        'hayop'),
  ('Oso',           'hayop'),
  ('Dugong',        'hayop'),
  ('Ibon',          'hayop'),
  ('Isda',          'hayop');

-- =============================================================
-- bagay (Object)
-- =============================================================
INSERT INTO henyo_words (word, category) VALUES
  ('Payong',        'bagay'),
  ('Relo',          'bagay'),
  ('Telepono',      'bagay'),
  ('Upuan',         'bagay'),
  ('Kotse',         'bagay'),
  ('Libro',         'bagay'),
  ('Pinto',         'bagay'),
  ('Salamin',       'bagay'),
  ('Sapatos',       'bagay'),
  ('Kandila',       'bagay'),
  ('Gunting',       'bagay'),
  ('Bola',          'bagay'),
  ('Kutsara',       'bagay'),
  ('Plato',         'bagay'),
  ('Bag',           'bagay'),
  ('Kama',          'bagay'),
  ('Mesa',          'bagay'),
  ('Aparador',      'bagay'),
  ('Banyo',         'bagay'),
  ('Eroplano',      'bagay'),
  ('Barko',         'bagay'),
  ('Bisikleta',     'bagay'),
  ('Pitaka',        'bagay'),
  ('Sombrero',      'bagay'),
  ('Medyas',        'bagay'),
  ('Tsinelas',      'bagay'),
  ('Langgam',       'bagay'),
  ('Higaan',        'bagay'),
  ('Unan',          'bagay'),
  ('Kumot',         'bagay'),
  ('Bote',          'bagay'),
  ('Pandesal',      'bagay'),
  ('Kahon',         'bagay'),
  ('Baso',          'bagay'),
  ('Telebisyon',    'bagay'),
  ('Pamaypay',        'bagay'),
  ('Yero',          'bagay'),
  ('Hagdan',        'bagay'),
  ('Tandang',       'bagay'),
  ('Poso',          'bagay'),
  ('Parol',         'bagay'),
  ('Kandado',       'bagay');

-- =============================================================
-- lugar (Place) — 42 words
-- =============================================================
INSERT INTO henyo_words (word, category) VALUES
  ('Maynila',        'lugar'),
  ('Boracay',        'lugar'),
  ('Palawan',        'lugar'),
  ('Cebu',           'lugar'),
  ('Davao',          'lugar'),
  ('Baguio',         'lugar'),
  ('Batangas',       'lugar'),
  ('Ilocos',         'lugar'),
  ('Mindanao',       'lugar'),
  ('Quezon City',    'lugar'),
  ('Vigan',          'lugar'),
  ('Chocolate Hills','lugar'),
  ('Taal',           'lugar'),
  ('Coron',          'lugar'),
  ('Subic',          'lugar'),
  ('Pampanga',       'lugar'),
  ('Bataan',         'lugar'),
  ('Cavite',         'lugar'),
  ('Rizal',          'lugar'),
  ('Leyte',          'lugar'),
  ('Samar',          'lugar'),
  ('Zamboanga',      'lugar'),
  ('Cagayan de Oro', 'lugar'),
  ('Naga City',      'lugar'),
  ('Iloilo',         'lugar'),
  ('Bacolod',        'lugar'),
  ('Tagaytay',       'lugar'),
  ('Bulacan',        'lugar'),
  ('Nueva Ecija',    'lugar'),
  ('La Union',       'lugar'),
  ('Pangasinan',     'lugar'),
  ('Isabela',        'lugar'),
  ('Tacloban',       'lugar'),
  ('General Santos', 'lugar'),
  ('Masbate',        'lugar'),
  ('Siargao',        'lugar'),
  ('El Nido',        'lugar'),
  ('Intramuros',     'lugar'),
  ('Pinatubo',       'lugar'),
  ('Mayon',          'lugar'),
  ('Apo',            'lugar'),
  ('Greece',            'lugar'),
  ('America',            'lugar'),
  ('Japan',            'lugar'),
  ('China',            'lugar'),
  ('Tokyo',            'lugar'),
  ('Kyoto',            'lugar'),
  ('Mt. Fuji',            'lugar'),
  ('Bali, Indonesia',            'lugar'),
  ('Paris',            'lugar'),
  ('Egypt',            'lugar'),
  ('Vietnam',            'lugar'),
  ('BGC',            'lugar'),
  ('Sydney',            'lugar'),
  ('Melbourne',            'lugar'),
  ('Vancouver',            'lugar'),
  ('New York',            'lugar'),
  ('Singapore',            'lugar'),
  ('Rome',            'lugar'),
  ('Angkor Wat',            'lugar'),
  ('Machu Picchu',            'lugar'),
  ('Bangkok',            'lugar'),
  ('Thailand',            'lugar'),
  ('Rio de Janeiro, Brazil',            'lugar'),
  ('Hong Kong',            'lugar'),
  ('Burj Khalifa',            'lugar'),
  ('Golden State Bridge',            'lugar');

-- ============================================================
-- Impostor Words
-- ============================================================

truncate table impostor_words restart identity cascade;

-- ============================================================
-- pagkain (Food) — 42 words
-- ============================================================
INSERT INTO impostor_words (word, category, difficulty, language) VALUES
  ('Adobo',           'pagkain', 'easy',   'filipino'),
  ('Sinigang',        'pagkain', 'easy',   'filipino'),
  ('Lechon',          'pagkain', 'easy',   'filipino'),
  ('Kare-kare',       'pagkain', 'medium', 'filipino'),
  ('Dinuguan',        'pagkain', 'medium', 'filipino'),
  ('Pancit',          'pagkain', 'easy',   'filipino'),
  ('Halo-halo',       'pagkain', 'easy',   'filipino'),
  ('Bulalo',          'pagkain', 'medium', 'filipino'),
  ('Tinola',          'pagkain', 'easy',   'filipino'),
  ('Sisig',           'pagkain', 'easy',   'filipino'),
  ('Arroz Caldo',     'pagkain', 'medium', 'filipino'),
  ('Lugaw',           'pagkain', 'easy',   'filipino'),
  ('Bicol Express',   'pagkain', 'medium', 'filipino'),
  ('Crispy Pata',     'pagkain', 'medium', 'filipino'),
  ('Kaldereta',       'pagkain', 'medium', 'filipino'),
  ('Mechado',         'pagkain', 'medium', 'filipino'),
  ('Menudo',          'pagkain', 'medium', 'filipino'),
  ('Afritada',        'pagkain', 'medium', 'filipino'),
  ('Paksiw',          'pagkain', 'medium', 'filipino'),
  ('Nilaga',          'pagkain', 'easy',   'filipino'),
  ('Inasal',          'pagkain', 'easy',   'filipino'),
  ('Kwek-kwek',       'pagkain', 'easy',   'filipino'),
  ('Fishball',        'pagkain', 'easy',   'mixed'),
  ('Balut',           'pagkain', 'medium', 'filipino'),
  ('Bibingka',        'pagkain', 'easy',   'filipino'),
  ('Puto',            'pagkain', 'easy',   'filipino'),
  ('Kutsinta',        'pagkain', 'medium', 'filipino'),
  ('Leche Flan',      'pagkain', 'easy',   'filipino'),
  ('Turon',           'pagkain', 'easy',   'filipino'),
  ('Palitaw',         'pagkain', 'medium', 'filipino'),
  ('Buko Pandan',     'pagkain', 'easy',   'filipino'),
  ('Maja Blanca',     'pagkain', 'medium', 'filipino'),
  ('Champorado',      'pagkain', 'easy',   'filipino'),
  ('Tocino',          'pagkain', 'easy',   'filipino'),
  ('Longganisa',      'pagkain', 'easy',   'filipino'),
  ('Tapa',            'pagkain', 'easy',   'filipino'),
  ('Daing',           'pagkain', 'easy',   'filipino'),
  ('Kilawin',         'pagkain', 'medium', 'filipino'),
  ('Kinilaw',         'pagkain', 'medium', 'filipino'),
  ('Pinakbet',        'pagkain', 'medium', 'filipino'),
  ('Utan Bisaya',     'pagkain', 'hard',   'filipino'),
  ('Batchoy',         'pagkain', 'medium', 'filipino');

-- ============================================================
-- hayop (Animal) — 42 words
-- ============================================================
INSERT INTO impostor_words (word, category, difficulty, language) VALUES
  ('Kalabaw',         'hayop',   'easy',   'filipino'),
  ('Baboy',           'hayop',   'easy',   'filipino'),
  ('Manok',           'hayop',   'easy',   'filipino'),
  ('Kambing',         'hayop',   'easy',   'filipino'),
  ('Pusa',            'hayop',   'easy',   'filipino'),
  ('Aso',             'hayop',   'easy',   'filipino'),
  ('Daga',            'hayop',   'easy',   'filipino'),
  ('Palaka',          'hayop',   'easy',   'filipino'),
  ('Ahas',            'hayop',   'medium', 'filipino'),
  ('Agila',           'hayop',   'medium', 'filipino'),
  ('Pawikan',         'hayop',   'medium', 'filipino'),
  ('Tamaraw',         'hayop',   'hard',   'filipino'),
  ('Maya',            'hayop',   'medium', 'filipino'),
  ('Kalapati',        'hayop',   'easy',   'filipino'),
  ('Papaya',          'hayop',   'easy',   'filipino'),
  ('Buwaya',          'hayop',   'easy',   'filipino'),
  ('Baboy Ramo',      'hayop',   'medium', 'filipino'),
  ('Bayawak',         'hayop',   'medium', 'filipino'),
  ('Uwak',            'hayop',   'easy',   'filipino'),
  ('Ibon',            'hayop',   'easy',   'filipino'),
  ('Isda',            'hayop',   'easy',   'filipino'),
  ('Hipon',           'hayop',   'easy',   'filipino'),
  ('Alimango',        'hayop',   'medium', 'filipino'),
  ('Pugad',           'hayop',   'medium', 'filipino'),
  ('Kabayo',          'hayop',   'easy',   'filipino'),
  ('Baka',            'hayop',   'easy',   'filipino'),
  ('Kambing',         'hayop',   'easy',   'filipino'),
  ('Pagong',          'hayop',   'easy',   'filipino'),
  ('Tuko',            'hayop',   'medium', 'filipino'),
  ('Tipaklong',       'hayop',   'easy',   'filipino'),
  ('Lamok',           'hayop',   'easy',   'filipino'),
  ('Langaw',          'hayop',   'easy',   'filipino'),
  ('Langgam',         'hayop',   'easy',   'filipino'),
  ('Pugo',            'hayop',   'medium', 'filipino'),
  ('Tandang',         'hayop',   'medium', 'filipino'),
  ('Alibangbang',     'hayop',   'medium', 'filipino'),
  ('Balingasa',       'hayop',   'hard',   'filipino'),
  ('Lobo',            'hayop',   'easy',   'filipino'),
  ('Kalabaw',         'hayop',   'easy',   'filipino'),
  ('Elepante',        'hayop',   'easy',   'filipino'),
  ('Leon',            'hayop',   'easy',   'filipino'),
  ('Unggoy',          'hayop',   'easy',   'filipino');

-- ============================================================
-- lugar (Place) — 42 words
-- ============================================================
INSERT INTO impostor_words (word, category, difficulty, language) VALUES
  ('Maynila',         'lugar',   'easy',   'filipino'),
  ('Cebu',            'lugar',   'easy',   'filipino'),
  ('Davao',           'lugar',   'easy',   'filipino'),
  ('Boracay',         'lugar',   'easy',   'filipino'),
  ('Palawan',         'lugar',   'easy',   'filipino'),
  ('Batangas',        'lugar',   'medium', 'filipino'),
  ('Baguio',          'lugar',   'easy',   'filipino'),
  ('Iloilo',          'lugar',   'medium', 'filipino'),
  ('Zamboanga',       'lugar',   'medium', 'filipino'),
  ('Vigan',           'lugar',   'medium', 'filipino'),
  ('Tagaytay',        'lugar',   'easy',   'filipino'),
  ('Naga',            'lugar',   'medium', 'filipino'),
  ('Cagayan de Oro',  'lugar',   'medium', 'filipino'),
  ('Quezon City',     'lugar',   'easy',   'filipino'),
  ('Makati',          'lugar',   'easy',   'filipino'),
  ('Cavite',          'lugar',   'medium', 'filipino'),
  ('Pampanga',        'lugar',   'medium', 'filipino'),
  ('Bulacan',         'lugar',   'medium', 'filipino'),
  ('Laguna',          'lugar',   'easy',   'filipino'),
  ('Rizal',           'lugar',   'easy',   'filipino'),
  ('Mindanao',        'lugar',   'easy',   'filipino'),
  ('Visayas',         'lugar',   'easy',   'filipino'),
  ('Luzon',           'lugar',   'easy',   'filipino'),
  ('Cordillera',      'lugar',   'medium', 'filipino'),
  ('Bataan',          'lugar',   'medium', 'filipino'),
  ('Subic',           'lugar',   'medium', 'filipino'),
  ('Olongapo',        'lugar',   'medium', 'filipino'),
  ('Puerto Princesa', 'lugar',   'medium', 'filipino'),
  ('El Nido',         'lugar',   'medium', 'filipino'),
  ('Coron',           'lugar',   'hard',   'filipino'),
  ('Siargao',         'lugar',   'medium', 'filipino'),
  ('Camiguin',        'lugar',   'medium', 'filipino'),
  ('Bantayan',        'lugar',   'hard',   'filipino'),
  ('Samal',           'lugar',   'hard',   'filipino'),
  ('Calamba',         'lugar',   'medium', 'filipino'),
  ('Lipa',            'lugar',   'medium', 'filipino'),
  ('Legazpi',         'lugar',   'medium', 'filipino'),
  ('Tacloban',        'lugar',   'medium', 'filipino'),
  ('Tuguegarao',      'lugar',   'hard',   'filipino'),
  ('Laoag',           'lugar',   'hard',   'filipino'),
  ('San Fernando',    'lugar',   'medium', 'filipino'),
  ('Antipolo',        'lugar',   'easy',   'filipino');

-- ============================================================
-- tao (Person) — 42 words
-- ============================================================
INSERT INTO impostor_words (word, category, difficulty, language) VALUES
  ('Guro',            'tao',     'easy',   'filipino'),
  ('Doktor',          'tao',     'easy',   'filipino'),
  ('Sundalo',         'tao',     'easy',   'filipino'),
  ('Manlalaro',       'tao',     'easy',   'filipino'),
  ('Magsasaka',       'tao',     'easy',   'filipino'),
  ('Mangingisda',     'tao',     'easy',   'filipino'),
  ('Abogado',         'tao',     'medium', 'filipino'),
  ('Piloto',          'tao',     'medium', 'filipino'),
  ('Kusinero',        'tao',     'easy',   'filipino'),
  ('Artista',         'tao',     'easy',   'filipino'),
  ('Pangulo',         'tao',     'medium', 'filipino'),
  ('Pulis',           'tao',     'easy',   'filipino'),
  ('Bombero',         'tao',     'easy',   'filipino'),
  ('Inhinyero',       'tao',     'medium', 'filipino'),
  ('Nars',            'tao',     'easy',   'filipino'),
  ('Dentista',        'tao',     'medium', 'filipino'),
  ('Tindero',         'tao',     'easy',   'filipino'),
  ('Karpintero',      'tao',     'easy',   'filipino'),
  ('Mananahi',        'tao',     'medium', 'filipino'),
  ('Manggagamot',     'tao',     'medium', 'filipino'),
  ('Mangungulam',     'tao',     'hard',   'filipino'),
  ('Manganganta',     'tao',     'easy',   'filipino'),
  ('Manunulat',       'tao',     'medium', 'filipino'),
  ('Pintor',          'tao',     'easy',   'filipino'),
  ('Eskultor',        'tao',     'medium', 'filipino'),
  ('Boksingero',      'tao',     'easy',   'filipino'),
  ('Manlalangoy',     'tao',     'easy',   'filipino'),
  ('Batik',           'tao',     'medium', 'filipino'),
  ('Mangbabarang',    'tao',     'hard',   'filipino'),
  ('Lolo',            'tao',     'easy',   'filipino'),
  ('Lola',            'tao',     'easy',   'filipino'),
  ('Anak',            'tao',     'easy',   'filipino'),
  ('Kapatid',         'tao',     'easy',   'filipino'),
  ('Kaibigan',        'tao',     'easy',   'filipino'),
  ('Katekista',       'tao',     'hard',   'filipino'),
  ('Alkalde',         'tao',     'medium', 'filipino'),
  ('Senador',         'tao',     'medium', 'filipino'),
  ('Gobernador',      'tao',     'medium', 'filipino'),
  ('Obispo',          'tao',     'medium', 'filipino'),
  ('Pari',            'tao',     'easy',   'filipino'),
  ('Pastor',          'tao',     'easy',   'filipino'),
  ('Atletang Pilipino','tao',    'medium', 'filipino');

-- ============================================================
-- bagay (Object) — 42 words
-- ============================================================
INSERT INTO impostor_words (word, category, difficulty, language) VALUES
  ('Telepono',        'bagay',   'easy',   'filipino'),
  ('Relo',            'bagay',   'easy',   'filipino'),
  ('Sapatos',         'bagay',   'easy',   'filipino'),
  ('Salamin',         'bagay',   'easy',   'filipino'),
  ('Libro',           'bagay',   'easy',   'filipino'),
  ('Payong',          'bagay',   'easy',   'filipino'),
  ('Gitara',          'bagay',   'easy',   'filipino'),
  ('Kandila',         'bagay',   'easy',   'filipino'),
  ('Palayok',         'bagay',   'medium', 'filipino'),
  ('Kutsilyo',        'bagay',   'easy',   'filipino'),
  ('Bangka',          'bagay',   'easy',   'filipino'),
  ('Poso',            'bagay',   'medium', 'filipino'),
  ('Higaan',          'bagay',   'easy',   'filipino'),
  ('Upuan',           'bagay',   'easy',   'filipino'),
  ('Mesa',            'bagay',   'easy',   'filipino'),
  ('Pinto',           'bagay',   'easy',   'filipino'),
  ('Bintana',         'bagay',   'easy',   'filipino'),
  ('Bag',             'bagay',   'easy',   'mixed'),
  ('Sombrero',        'bagay',   'easy',   'filipino'),
  ('Sinturon',        'bagay',   'easy',   'filipino'),
  ('Hikaw',           'bagay',   'easy',   'filipino'),
  ('Kuwintas',        'bagay',   'easy',   'filipino'),
  ('Singsing',        'bagay',   'easy',   'filipino'),
  ('Fan',             'bagay',   'easy',   'mixed'),
  ('Pamaypay',        'bagay',   'medium', 'filipino'),
  ('Tambol',          'bagay',   'easy',   'filipino'),
  ('Playdoh',         'bagay',   'easy',   'english'),
  ('Lumang Radyo',    'bagay',   'medium', 'filipino'),
  ('Baybayin',        'bagay',   'hard',   'filipino'),
  ('Baul',            'bagay',   'medium', 'filipino'),
  ('Bangketa',        'bagay',   'medium', 'filipino'),
  ('Pampagawa',       'bagay',   'hard',   'filipino'),
  ('Barya',           'bagay',   'easy',   'filipino'),
  ('Perang Papel',    'bagay',   'easy',   'filipino'),
  ('Pitaka',          'bagay',   'easy',   'filipino'),
  ('Bag ng Paaralan', 'bagay',   'easy',   'filipino'),
  ('Lapis',           'bagay',   'easy',   'filipino'),
  ('Panulat',         'bagay',   'easy',   'filipino'),
  ('Gunting',         'bagay',   'easy',   'filipino'),
  ('Kalawit',         'bagay',   'medium', 'filipino'),
  ('Pala',            'bagay',   'easy',   'filipino'),
  ('Martilyo',        'bagay',   'easy',   'filipino');

-- ============================================================
-- palaro (Sport / Game) — 42 words
-- ============================================================
INSERT INTO impostor_words (word, category, difficulty, language) VALUES
  ('Basketball',      'palaro',  'easy',   'english'),
  ('Volleyball',      'palaro',  'easy',   'english'),
  ('Sipa',            'palaro',  'easy',   'filipino'),
  ('Patintero',       'palaro',  'easy',   'filipino'),
  ('Tumbang Preso',   'palaro',  'easy',   'filipino'),
  ('Sungka',          'palaro',  'medium', 'filipino'),
  ('Agawan Base',     'palaro',  'medium', 'filipino'),
  ('Luksong Tinik',   'palaro',  'easy',   'filipino'),
  ('Boxing',          'palaro',  'easy',   'english'),
  ('Badminton',       'palaro',  'easy',   'english'),
  ('Swimming',        'palaro',  'easy',   'english'),
  ('Ajedrez',         'palaro',  'medium', 'filipino'),
  ('Football',        'palaro',  'easy',   'english'),
  ('Piko',            'palaro',  'easy',   'filipino'),
  ('Taguan',          'palaro',  'easy',   'filipino'),
  ('Habulan',         'palaro',  'easy',   'filipino'),
  ('Chinese Garter',  'palaro',  'medium', 'english'),
  ('Trumpo',          'palaro',  'medium', 'filipino'),
  ('Saranggola',      'palaro',  'easy',   'filipino'),
  ('Palo Sebo',       'palaro',  'medium', 'filipino'),
  ('Bato Bato Pick',  'palaro',  'easy',   'mixed'),
  ('Sepak Takraw',    'palaro',  'medium', 'mixed'),
  ('Arnis',           'palaro',  'medium', 'filipino'),
  ('Bowling',         'palaro',  'easy',   'english'),
  ('Tennis',          'palaro',  'easy',   'english'),
  ('Golf',            'palaro',  'easy',   'english'),
  ('Billiards',       'palaro',  'easy',   'english'),
  ('Chess',           'palaro',  'easy',   'english'),
  ('Darts',           'palaro',  'easy',   'english'),
  ('Dart',            'palaro',  'easy',   'english'),
  ('Laro ng Laro',    'palaro',  'easy',   'filipino'),
  ('Palosebo',        'palaro',  'medium', 'filipino'),
  ('Larong Kalye',    'palaro',  'easy',   'filipino'),
  ('Jackstone',       'palaro',  'easy',   'mixed'),
  ('Dampa',           'palaro',  'medium', 'filipino'),
  ('Sungka',          'palaro',  'medium', 'filipino'),
  ('Racing',          'palaro',  'easy',   'english'),
  ('Marathon',        'palaro',  'medium', 'english'),
  ('Gymnastics',      'palaro',  'medium', 'english'),
  ('Karate',          'palaro',  'medium', 'mixed'),
  ('Judo',            'palaro',  'medium', 'english'),
  ('Taekwondo',       'palaro',  'medium', 'english');

-- ============================================================
-- pelikula (Movie / Show) — 42 words
-- ============================================================
INSERT INTO impostor_words (word, category, difficulty, language) VALUES
  ('Enteng Kabisote',     'pelikula', 'easy',   'filipino'),
  ('Shake Rattle Roll',   'pelikula', 'medium', 'mixed'),
  ('Titanic',             'pelikula', 'easy',   'english'),
  ('Avengers',            'pelikula', 'easy',   'english'),
  ('Star Wars',           'pelikula', 'easy',   'english'),
  ('Harry Potter',        'pelikula', 'easy',   'english'),
  ('Bata Bata Paano Ka Ginawa', 'pelikula', 'hard', 'filipino'),
  ('Madrasta',            'pelikula', 'medium', 'filipino'),
  ('Sana Maulit Muli',    'pelikula', 'easy',   'filipino'),
  ('Ang Tanging Pamilya', 'pelikula', 'medium', 'filipino'),
  ('Starting Over Again', 'pelikula', 'easy',   'filipino'),
  ('No Other Woman',      'pelikula', 'easy',   'english'),
  ('Four Sisters and a Wedding', 'pelikula', 'medium', 'mixed'),
  ('My Big Bossing',      'pelikula', 'medium', 'mixed'),
  ('Juan dela Cruz',      'pelikula', 'easy',   'filipino'),
  ('FPJ ang Probinsyano', 'pelikula', 'easy',   'filipino'),
  ('Encantadia',          'pelikula', 'easy',   'filipino'),
  ('ABS-CBN Series',      'pelikula', 'easy',   'mixed'),
  ('GMA Drama',           'pelikula', 'easy',   'mixed'),
  ('Aliens vs Zombies',   'pelikula', 'medium', 'english'),
  ('Thor',                'pelikula', 'easy',   'english'),
  ('Spider-Man',          'pelikula', 'easy',   'english'),
  ('Batman',              'pelikula', 'easy',   'english'),
  ('Superman',            'pelikula', 'easy',   'english'),
  ('Darna',               'pelikula', 'easy',   'filipino'),
  ('Alyas Robin Hood',    'pelikula', 'medium', 'filipino'),
  ('Panday',              'pelikula', 'easy',   'filipino'),
  ('Zsazsa Zaturnnah',    'pelikula', 'medium', 'mixed'),
  ('Kimmy Dora',          'pelikula', 'easy',   'filipino'),
  ('Para sa Hopeless Romantic', 'pelikula', 'medium', 'mixed'),
  ('I Love You Goodbye',  'pelikula', 'easy',   'english'),
  ('Die Hard',            'pelikula', 'easy',   'english'),
  ('Fast and Furious',    'pelikula', 'easy',   'english'),
  ('Transformers',        'pelikula', 'easy',   'english'),
  ('Lord of the Rings',   'pelikula', 'medium', 'english'),
  ('Frozen',              'pelikula', 'easy',   'english'),
  ('Moana',               'pelikula', 'easy',   'english'),
  ('Encanto',             'pelikula', 'easy',   'english'),
  ('Coco',                'pelikula', 'easy',   'english'),
  ('Vivo',                'pelikula', 'medium', 'english'),
  ('Kita Kita',           'pelikula', 'easy',   'filipino'),
  ('Heneral Luna',        'pelikula', 'easy',   'filipino');

-- ============================================================
-- sports (Sports) — 42 words
-- ============================================================
INSERT INTO impostor_words (word, category, difficulty, language) VALUES
  ('Basketball',      'sports',  'easy',   'english'),
  ('Football',        'sports',  'easy',   'english'),
  ('Volleyball',      'sports',  'easy',   'english'),
  ('Tennis',          'sports',  'easy',   'english'),
  ('Golf',            'sports',  'easy',   'english'),
  ('Boxing',          'sports',  'easy',   'english'),
  ('Swimming',        'sports',  'easy',   'english'),
  ('Athletics',       'sports',  'medium', 'english'),
  ('Gymnastics',      'sports',  'medium', 'english'),
  ('Cycling',         'sports',  'easy',   'english'),
  ('Martial Arts',    'sports',  'medium', 'english'),
  ('Badminton',       'sports',  'easy',   'english'),
  ('Table Tennis',    'sports',  'easy',   'english'),
  ('Archery',         'sports',  'medium', 'english'),
  ('Shooting',        'sports',  'medium', 'english'),
  ('Wrestling',       'sports',  'easy',   'english'),
  ('Judo',            'sports',  'medium', 'english'),
  ('Taekwondo',       'sports',  'medium', 'english'),
  ('Karate',          'sports',  'medium', 'english'),
  ('Rowing',          'sports',  'medium', 'english'),
  ('Sailing',         'sports',  'medium', 'english'),
  ('Triathlon',       'sports',  'hard',   'english'),
  ('Marathon',        'sports',  'medium', 'english'),
  ('Weightlifting',   'sports',  'medium', 'english'),
  ('Surfing',         'sports',  'medium', 'english'),
  ('Skateboarding',   'sports',  'medium', 'english'),
  ('Baseball',        'sports',  'easy',   'english'),
  ('Softball',        'sports',  'easy',   'english'),
  ('Cricket',         'sports',  'medium', 'english'),
  ('Rugby',           'sports',  'medium', 'english'),
  ('Water Polo',      'sports',  'medium', 'english'),
  ('Diving',          'sports',  'medium', 'english'),
  ('Fencing',         'sports',  'hard',   'english'),
  ('Equestrian',      'sports',  'hard',   'english'),
  ('Biathlon',        'sports',  'hard',   'english'),
  ('Bobsled',         'sports',  'hard',   'english'),
  ('Ice Hockey',      'sports',  'medium', 'english'),
  ('Figure Skating',  'sports',  'medium', 'english'),
  ('Ski Jump',        'sports',  'hard',   'english'),
  ('Curling',         'sports',  'hard',   'english'),
  ('Esports',         'sports',  'easy',   'english'),
  ('Chess Boxing',    'sports',  'hard',   'english');
