-- ============================================================
-- Pinoy Henyo
-- ============================================================

truncate table henyo_words restart identity cascade;

-- =============================================================
-- pagkain (Food)
-- =============================================================
INSERT INTO henyo_words (word, category) VALUES
  ('Adobo', 'pagkain'),
  ('Sinigang', 'pagkain'),
  ('Lechon', 'pagkain'),
  ('Balut', 'pagkain'),
  ('Halo-Halo', 'pagkain'),
  ('Pancit', 'pagkain'),
  ('Kare-Kare', 'pagkain'),
  ('Dinuguan', 'pagkain'),
  ('Lumpia', 'pagkain'),
  ('Bibingka', 'pagkain'),
  ('Tapsilog', 'pagkain'),
  ('Sisig', 'pagkain'),
  ('Buko Pandan', 'pagkain'),
  ('Champorado', 'pagkain'),
  ('Kwek-Kwek', 'pagkain'),
  ('Tinola', 'pagkain'),
  ('Arroz Caldo', 'pagkain'),
  ('Bulalo', 'pagkain'),
  ('Menudo', 'pagkain'),
  ('Caldereta', 'pagkain'),
  ('Crispy Pata', 'pagkain'),
  ('Taho', 'pagkain'),
  ('Palitaw', 'pagkain'),
  ('Puto', 'pagkain'),
  ('Biko', 'pagkain'),
  ('Mami', 'pagkain'),
  ('Lomi', 'pagkain'),
  ('Kuchinta', 'pagkain'),
  ('Leche Flan', 'pagkain'),
  ('Bangus', 'pagkain'),
  ('Tortang Talong', 'pagkain'),
  ('Ginisang Ampalaya', 'pagkain'),
  ('Inasal', 'pagkain'),
  ('Sinuglaw', 'pagkain'),
  ('Puto Bumbong', 'pagkain'),
  ('Ensaymada', 'pagkain'),
  ('Pandesal', 'pagkain'),
  ('Turon', 'pagkain'),
  ('Ginataan', 'pagkain'),
  ('Ube Halaya', 'pagkain'),
  ('Goto', 'pagkain'),
  ('Spaghetti', 'pagkain'),
  ('Carbonara', 'pagkain'),
  ('Lasagna', 'pagkain'),
  ('Pizza', 'pagkain'),
  ('Isaw', 'pagkain');

-- =============================================================
-- tao (Person)
-- =============================================================
INSERT INTO henyo_words (word, category) VALUES
  ('Jose Rizal',         'tao'),
  ('Coco Martin',        'tao'),
  ('Manny Pacquiao',     'tao'),
  ('Sarah Geronimo',     'tao'),
  ('Ninoy Aquino',       'tao'),
  ('Vice Ganda',         'tao'),
  ('Lea Salonga',        'tao'),
  ('Lapu-Lapu',          'tao'),
  ('Kim Chiu',           'tao'),
  ('Efren Reyes',        'tao'),
  ('Kathryn Bernardo',   'tao'),
  ('Andres Bonifacio',   'tao'),
  ('Cory Aquino',        'tao'),
  ('Bamboo',             'tao'),
  ('Daniel Padilla',     'tao'),
  ('Rodrigo Duterte',    'tao'),
  ('Imelda Marcos',      'tao'),
  ('Fernando Poe Jr',    'tao'),
  ('Charice Pempengco',  'tao'),
  ('Regine Velasquez',   'tao'),
  ('Gary Valenciano',    'tao'),
  ('Dolphy',             'tao'),
  ('Nora Aunor',         'tao'),
  ('Aga Muhlach',        'tao'),
  ('Anne Curtis',        'tao'),
  ('Alden Richards',     'tao'),
  ('Maine Mendoza',      'tao'),
  ('Sandara Park',       'tao'),
  ('Liza Soberano',      'tao'),
  ('Enrique Gil',        'tao'),
  ('Piolo Pascual',      'tao'),
  ('Sharon Cuneta',      'tao'),
  ('Emilio Aguinaldo',   'tao'),
  ('BINI',               'tao'),
  ('SB19',               'tao'),
  ('Lani Misalucha',     'tao'),
  ('Freddie Aguilar',    'tao'),
  ('Ramon Magsaysay',    'tao'),
  ('Donald Trump',    'tao'),
  ('Harry Styles',    'tao'),
  ('Zayn Malik',    'tao'),
  ('Justin Bieber',    'tao'),
  ('Taylor Swift',    'tao'),
  ('Gerald Anderson',    'tao'),
  ('Selena Gomez',    'tao'),
  ('Kim Jong Un',    'tao'),
  ('Alex Eala',    'tao'),
  ('Michael Jackson',    'tao'),
  ('Kobe Bryant',    'tao'),
  ('Lebron James',    'tao'),
  ('Bol Bol',    'tao'),
  ('Stephen Curry',    'tao'),
  ('Tiger Woods',    'tao'),
  ('Michael Phelps',    'tao'),
  ('Barack Obama',    'tao'),
  ('John Wick',    'tao'),
  ('One Direction',    'tao'),
  ('Leonardo Da Vinci',    'tao'),
  ('Leonardo Dicaprio',    'tao'),
  ('Megan Fox',    'tao'),
  ('Jennifer Aniston',    'tao'),
  ('Jennifer Lawrence',    'tao'),
  ('Jennifer Lawrence',    'tao'),
  ('Christiano Ronaldo',    'tao'),
  ('Lionel Messi',    'tao'),
  ('The Rock',    'tao'),
  ('Billie Eilish',    'tao');

-- =============================================================
-- hayop (Animal)
-- =============================================================
INSERT INTO henyo_words (word, category) VALUES
  ('Kalabaw',       'hayop'),
  ('Maya',          'hayop'),
  ('Tarsier',       'hayop'),
  ('Pawikan',       'hayop'),
  ('Agila',         'hayop'),
  ('Daga',          'hayop'),
  ('Baboy-Damo',    'hayop'),
  ('Butanding',     'hayop'),
  ('Kabayo',        'hayop'),
  ('Lobo',          'hayop'),
  ('Pusa',          'hayop'),
  ('Aso',           'hayop'),
  ('Balyena',       'hayop'),
  ('Itik',          'hayop'),
  ('Manok',         'hayop'),
  ('Kambing',       'hayop'),
  ('Baka',          'hayop'),
  ('Baboy',         'hayop'),
  ('Kuneho',        'hayop'),
  ('Palaka',        'hayop'),
  ('Ahas',          'hayop'),
  ('Bayawak',       'hayop'),
  ('Tamaraw',       'hayop'),
  ('Kalapati',      'hayop'),
  ('Uwak',          'hayop'),
  ('Dolphin',        'hayop'),
  ('Pating',        'hayop'),
  ('Pugad',         'hayop'),
  ('Elepante',      'hayop'),
  ('Leon',          'hayop'),
  ('Tigre',         'hayop'),
  ('Unggoy',        'hayop'),
  ('Oso',           'hayop'),
  ('Dugong',        'hayop'),
  ('Ibon',          'hayop'),
  ('Isda',          'hayop');

-- =============================================================
-- bagay (Object)
-- =============================================================
INSERT INTO henyo_words (word, category) VALUES
  ('Payong',        'bagay'),
  ('Relo',          'bagay'),
  ('Telepono',      'bagay'),
  ('Upuan',         'bagay'),
  ('Kotse',         'bagay'),
  ('Libro',         'bagay'),
  ('Pinto',         'bagay'),
  ('Salamin',       'bagay'),
  ('Sapatos',       'bagay'),
  ('Kandila',       'bagay'),
  ('Gunting',       'bagay'),
  ('Bola',          'bagay'),
  ('Kutsara',       'bagay'),
  ('Plato',         'bagay'),
  ('Bag',           'bagay'),
  ('Kama',          'bagay'),
  ('Mesa',          'bagay'),
  ('Aparador',      'bagay'),
  ('Banyo',         'bagay'),
  ('Eroplano',      'bagay'),
  ('Barko',         'bagay'),
  ('Bisikleta',     'bagay'),
  ('Pitaka',        'bagay'),
  ('Sombrero',      'bagay'),
  ('Medyas',        'bagay'),
  ('Tsinelas',      'bagay'),
  ('Langgam',       'bagay'),
  ('Higaan',        'bagay'),
  ('Unan',          'bagay'),
  ('Kumot',         'bagay'),
  ('Bote',          'bagay'),
  ('Pandesal',      'bagay'),
  ('Kahon',         'bagay'),
  ('Baso',          'bagay'),
  ('Telebisyon',    'bagay'),
  ('Pamaypay',        'bagay'),
  ('Yero',          'bagay'),
  ('Hagdan',        'bagay'),
  ('Tandang',       'bagay'),
  ('Poso',          'bagay'),
  ('Parol',         'bagay'),
  ('Kandado',       'bagay');

-- =============================================================
-- lugar (Place) — 42 words
-- =============================================================
INSERT INTO henyo_words (word, category) VALUES
  ('Maynila',        'lugar'),
  ('Boracay',        'lugar'),
  ('Palawan',        'lugar'),
  ('Cebu',           'lugar'),
  ('Davao',          'lugar'),
  ('Baguio',         'lugar'),
  ('Batangas',       'lugar'),
  ('Ilocos',         'lugar'),
  ('Mindanao',       'lugar'),
  ('Quezon City',    'lugar'),
  ('Vigan',          'lugar'),
  ('Chocolate Hills','lugar'),
  ('Taal',           'lugar'),
  ('Coron',          'lugar'),
  ('Subic',          'lugar'),
  ('Pampanga',       'lugar'),
  ('Bataan',         'lugar'),
  ('Cavite',         'lugar'),
  ('Rizal',          'lugar'),
  ('Leyte',          'lugar'),
  ('Samar',          'lugar'),
  ('Zamboanga',      'lugar'),
  ('Cagayan de Oro', 'lugar'),
  ('Naga City',      'lugar'),
  ('Iloilo',         'lugar'),
  ('Bacolod',        'lugar'),
  ('Tagaytay',       'lugar'),
  ('Bulacan',        'lugar'),
  ('Nueva Ecija',    'lugar'),
  ('La Union',       'lugar'),
  ('Pangasinan',     'lugar'),
  ('Isabela',        'lugar'),
  ('Tacloban',       'lugar'),
  ('General Santos', 'lugar'),
  ('Masbate',        'lugar'),
  ('Siargao',        'lugar'),
  ('El Nido',        'lugar'),
  ('Intramuros',     'lugar'),
  ('Pinatubo',       'lugar'),
  ('Mayon',          'lugar'),
  ('Apo',            'lugar'),
  ('Greece',            'lugar'),
  ('America',            'lugar'),
  ('Japan',            'lugar'),
  ('China',            'lugar'),
  ('Tokyo',            'lugar'),
  ('Kyoto',            'lugar'),
  ('Mt. Fuji',            'lugar'),
  ('Bali, Indonesia',            'lugar'),
  ('Paris',            'lugar'),
  ('Egypt',            'lugar'),
  ('Vietnam',            'lugar'),
  ('BGC',            'lugar'),
  ('Sydney',            'lugar'),
  ('Melbourne',            'lugar'),
  ('Vancouver',            'lugar'),
  ('New York',            'lugar'),
  ('Singapore',            'lugar'),
  ('Rome',            'lugar'),
  ('Angkor Wat',            'lugar'),
  ('Machu Picchu',            'lugar'),
  ('Bangkok',            'lugar'),
  ('Thailand',            'lugar'),
  ('Rio de Janeiro, Brazil',            'lugar'),
  ('Hong Kong',            'lugar'),
  ('Burj Khalifa',            'lugar'),
  ('Golden State Bridge',            'lugar');
