-- ============================================================
-- Pinoy Henyo
-- ============================================================

truncate table henyo_words restart identity cascade;

-- =============================================================
-- pagkain (Food) — 42 words
-- =============================================================
INSERT INTO henyo_words (word, category, difficulty, language, hint) VALUES
  ('Adobo',          'pagkain', 'easy',   'filipino', 'Sikat na ulam ng Pilipinas'),
  ('Sinigang',       'pagkain', 'easy',   'filipino', 'Maasim na sabaw'),
  ('Lechon',         'pagkain', 'easy',   'filipino', 'Ihinaw na baboy'),
  ('Balut',          'pagkain', 'medium', 'filipino', 'Itlog ng pato'),
  ('Halo-Halo',      'pagkain', 'easy',   'filipino', 'Malamig na dessert'),
  ('Pancit',         'pagkain', 'easy',   'filipino', 'Pansit na ulam'),
  ('Kare-Kare',      'pagkain', 'medium', 'filipino', 'May mani na sarsa'),
  ('Dinuguan',       'pagkain', 'medium', 'filipino', 'Itim na sabaw'),
  ('Lumpia',         'pagkain', 'easy',   'filipino', 'Nakabalot na pagkain'),
  ('Bibingka',       'pagkain', 'easy',   'filipino', 'Kakanin sa Pasko'),
  ('Tapsilog',       'pagkain', 'easy',   'filipino', 'Sikat na almusal'),
  ('Sisig',          'pagkain', 'easy',   'filipino', 'Pagkain mula sa Pampanga'),
  ('Buko Pandan',    'pagkain', 'easy',   'filipino', 'Berde na dessert'),
  ('Champorado',     'pagkain', 'easy',   'filipino', 'Mainit na chocolatey na lugaw'),
  ('Kwek-Kwek',      'pagkain', 'easy',   'filipino', 'Street food na itlog'),
  ('Tinola',         'pagkain', 'easy',   'filipino', 'Sopas na may manok'),
  ('Arroz Caldo',    'pagkain', 'medium', 'filipino', 'Malamig na lugaw na may manok'),
  ('Bulalo',         'pagkain', 'medium', 'filipino', 'Sabaw na may buto-buto'),
  ('Menudo',         'pagkain', 'easy',   'filipino', 'Ulam na may patatas'),
  ('Caldereta',      'pagkain', 'medium', 'filipino', 'Ulam na may kamatis'),
  ('Crispy Pata',    'pagkain', 'easy',   'filipino', 'Pritong paa ng baboy'),
  ('Taho',           'pagkain', 'easy',   'filipino', 'Mainit na tofu snack'),
  ('Palitaw',        'pagkain', 'medium', 'filipino', 'Kakanin na bilog'),
  ('Puto',           'pagkain', 'easy',   'filipino', 'Puting kakanin'),
  ('Biko',           'pagkain', 'easy',   'filipino', 'Matamis na kakanin'),
  ('Mami',           'pagkain', 'easy',   'filipino', 'Sabaw na may miki'),
  ('Lomi',           'pagkain', 'easy',   'filipino', 'Malapot na sabaw na may miki'),
  ('Kuchinta',       'pagkain', 'medium', 'filipino', 'Malagkit na kakanin na pula'),
  ('Leche Flan',     'pagkain', 'easy',   'filipino', 'Matamis na itlog na dessert'),
  ('Bangus',         'pagkain', 'easy',   'filipino', 'Pambansang isda'),
  ('Tortang Talong', 'pagkain', 'medium', 'filipino', 'Torta na may talong'),
  ('Ginisang Ampalaya','pagkain','medium','filipino', 'Mapait na gulay na ulam'),
  ('Inasal',         'pagkain', 'easy',   'filipino', 'Inihaw na manok sa Bacolod'),
  ('Sinuglaw',       'pagkain', 'hard',   'filipino', 'Kumbinasyon ng kinilaw at sinugba'),
  ('Puto Bumbong',   'pagkain', 'medium', 'filipino', 'Pulang kakanin sa Pasko'),
  ('Ensaymada',      'pagkain', 'easy',   'filipino', 'Matamis na tinapay'),
  ('Pan de Sal',     'pagkain', 'easy',   'filipino', 'Pamahaw na tinapay'),
  ('Turon',          'pagkain', 'easy',   'filipino', 'Pritong saging sa lumpia wrapper'),
  ('Kalamay',        'pagkain', 'medium', 'filipino', 'Malagkit at matamis na kakanin'),
  ('Ginataan',       'pagkain', 'easy',   'filipino', 'Pagkain na may gata'),
  ('Ube Halaya',     'pagkain', 'easy',   'filipino', 'Ube na jam'),
  ('Goto',           'pagkain', 'medium', 'filipino', 'Lugaw na may goto');

-- =============================================================
-- tao (Person) — 42 words
-- =============================================================
INSERT INTO henyo_words (word, category, difficulty, language, hint) VALUES
  ('Jose Rizal',         'tao', 'easy',   'filipino', 'Bayani ng Pilipinas'),
  ('Coco Martin',        'tao', 'easy',   'filipino', 'Artista'),
  ('Manny Pacquiao',     'tao', 'easy',   'filipino', 'Boksingero'),
  ('Sarah Geronimo',     'tao', 'easy',   'filipino', 'Mang-aawit at artista'),
  ('Ninoy Aquino',       'tao', 'medium', 'filipino', 'Yumaong politiko'),
  ('Vice Ganda',         'tao', 'easy',   'filipino', 'Komedyante'),
  ('Lea Salonga',        'tao', 'medium', 'filipino', 'Mang-aawit sa Broadway'),
  ('Lapu-Lapu',          'tao', 'easy',   'filipino', 'Datu ng Mactan'),
  ('Kim Chiu',           'tao', 'easy',   'filipino', 'Artista'),
  ('Efren Reyes',        'tao', 'hard',   'filipino', 'Kampeon sa billiards'),
  ('Kathryn Bernardo',   'tao', 'easy',   'filipino', 'Artista at mang-aawit'),
  ('Andres Bonifacio',   'tao', 'medium', 'filipino', 'Ama ng Katipunan'),
  ('Cory Aquino',        'tao', 'medium', 'filipino', 'Unang babaeng pangulo'),
  ('Bamboo',             'tao', 'medium', 'filipino', 'Sikat na rock singer'),
  ('Daniel Padilla',     'tao', 'easy',   'filipino', 'Artista at mang-aawit'),
  ('Rodrigo Duterte',    'tao', 'easy',   'filipino', 'Dating pangulo'),
  ('Imelda Marcos',      'tao', 'medium', 'filipino', 'Dating first lady'),
  ('Fernando Poe Jr',    'tao', 'medium', 'filipino', 'Hari ng Pelikula'),
  ('Charice Pempengco',  'tao', 'medium', 'filipino', 'International pop star'),
  ('Regine Velasquez',   'tao', 'easy',   'filipino', 'Asia''s Songbird'),
  ('Gary Valenciano',    'tao', 'easy',   'filipino', 'Mr. Pure Energy'),
  ('Dolphy',             'tao', 'medium', 'filipino', 'Hari ng Komedya'),
  ('Nora Aunor',         'tao', 'medium', 'filipino', 'The Superstar'),
  ('Aga Muhlach',        'tao', 'easy',   'filipino', 'Sikat na aktor'),
  ('Anne Curtis',        'tao', 'easy',   'filipino', 'Artista at host'),
  ('Alden Richards',     'tao', 'easy',   'filipino', 'Paboritong artista'),
  ('Maine Mendoza',      'tao', 'easy',   'filipino', 'Artista at komedyante'),
  ('Sandara Park',       'tao', 'medium', 'filipino', 'Korean-Filipino artista'),
  ('Liza Soberano',      'tao', 'easy',   'filipino', 'Artista'),
  ('Enrique Gil',        'tao', 'easy',   'filipino', 'Artista'),
  ('Piolo Pascual',      'tao', 'easy',   'filipino', 'Star ng mga babae'),
  ('Sharon Cuneta',      'tao', 'easy',   'filipino', 'Megastar'),
  ('Emilio Aguinaldo',   'tao', 'medium', 'filipino', 'Unang pangulo ng Pilipinas'),
  ('Artemio Ricarte',    'tao', 'hard',   'filipino', 'Heneral ng Pilipinas'),
  ('Bohol',              'tao', 'hard',   'filipino', 'Lalawigan'),
  ('BINI',               'tao', 'easy',   'filipino', 'OPM girl group'),
  ('SB19',               'tao', 'easy',   'filipino', 'Sikat na P-pop group'),
  ('Lani Misalucha',     'tao', 'medium', 'filipino', 'Asia''s Nightingale'),
  ('Freddie Aguilar',    'tao', 'medium', 'filipino', 'Mang-aawit ng Bayan Ko'),
  ('Ramon Magsaysay',    'tao', 'hard',   'filipino', 'Pangulo ng Pilipinas'),
  ('Bernardo Carpio',    'tao', 'hard',   'filipino', 'Alamat na higante'),
  ('Juan dela Cruz',     'tao', 'easy',   'filipino', 'Simbolo ng Pilipino');

-- =============================================================
-- hayop (Animal) — 42 words
-- =============================================================
INSERT INTO henyo_words (word, category, difficulty, language, hint) VALUES
  ('Kalabaw',       'hayop', 'easy',   'filipino', 'Pambansang hayop'),
  ('Maya',          'hayop', 'easy',   'filipino', 'Maliit na ibon'),
  ('Tarsier',       'hayop', 'medium', 'english',  'Maliit na hayop sa Bohol'),
  ('Pawikan',       'hayop', 'medium', 'filipino', 'Pagong sa dagat'),
  ('Agila',         'hayop', 'easy',   'filipino', 'Pambansang ibon'),
  ('Daga',          'hayop', 'easy',   'filipino', 'Maliit na hayop'),
  ('Baboy-Damo',    'hayop', 'medium', 'filipino', 'Ligaw na baboy'),
  ('Butanding',     'hayop', 'medium', 'filipino', 'Pinakamalaking isda'),
  ('Kabayo',        'hayop', 'easy',   'filipino', 'Sinakay na hayop'),
  ('Lobo',          'hayop', 'easy',   'filipino', 'Mababangis na aso'),
  ('Pusa',          'hayop', 'easy',   'filipino', 'Malambing na alagang hayop'),
  ('Aso',           'hayop', 'easy',   'filipino', 'Tapat na alagang hayop'),
  ('Tipaklong',     'hayop', 'easy',   'filipino', 'Lumukso-lukso sa damo'),
  ('Balyena',       'hayop', 'medium', 'filipino', 'Pinakamalaking hayop sa dagat'),
  ('Itik',          'hayop', 'easy',   'filipino', 'Ibon na lumalangoy'),
  ('Manok',         'hayop', 'easy',   'filipino', 'Hayop sa bukid'),
  ('Kambing',       'hayop', 'easy',   'filipino', 'Hayop na may sungay'),
  ('Baka',          'hayop', 'easy',   'filipino', 'Mapagbigay ng gatas'),
  ('Baboy',         'hayop', 'easy',   'filipino', 'Hayop na paborito sa lechon'),
  ('Kuneho',        'hayop', 'easy',   'filipino', 'Malambot at puting hayop'),
  ('Palaka',        'hayop', 'easy',   'filipino', 'Hayop na lumalangoy at lumuukso'),
  ('Ahas',          'hayop', 'easy',   'filipino', 'Mahabang gumagapang na hayop'),
  ('Bayawak',       'hayop', 'medium', 'filipino', 'Malaking biyak'),
  ('Tamaraw',       'hayop', 'hard',   'filipino', 'Endemic na kalabaw sa Mindoro'),
  ('Lawin',         'hayop', 'medium', 'filipino', 'Malaking ibon ng himpapawid'),
  ('Kalapati',      'hayop', 'easy',   'filipino', 'Ibon ng kapayapaan'),
  ('Uwak',          'hayop', 'easy',   'filipino', 'Itim na ibon'),
  ('Papagayo',      'hayop', 'easy',   'filipino', 'Makulay na ibon na nagsasalita'),
  ('Dolfin',        'hayop', 'easy',   'english',  'Matalinong hayop sa dagat'),
  ('Pating',        'hayop', 'medium', 'filipino', 'Mababangis na isda sa dagat'),
  ('Pugad',         'hayop', 'medium', 'filipino', 'Tahanan ng ibon'),
  ('Elepante',      'hayop', 'easy',   'filipino', 'Pinakamalaking hayop sa lupa'),
  ('Leon',          'hayop', 'easy',   'filipino', 'Hari ng kagubatan'),
  ('Tigre',         'hayop', 'easy',   'filipino', 'Malaking hayop na may guhit'),
  ('Unggoy',        'hayop', 'easy',   'filipino', 'Hayop na hawig sa tao'),
  ('Oso',           'hayop', 'easy',   'filipino', 'Malaking hayop sa kagubatan'),
  ('Penguino',      'hayop', 'easy',   'filipino', 'Ibon sa malamig na lugar'),
  ('Pangolin',      'hayop', 'hard',   'english',  'Hayop na may kaliskis'),
  ('Dugong',        'hayop', 'hard',   'english',  'Hayop sa dagat na pang-dagat na baka'),
  ('Musang',        'hayop', 'medium', 'filipino', 'Hayop na may masamang amoy'),
  ('Ibon',          'hayop', 'easy',   'filipino', 'Hayop na lumilipad'),
  ('Isda',          'hayop', 'easy',   'filipino', 'Hayop sa tubig');

-- =============================================================
-- bagay (Object) — 42 words
-- =============================================================
INSERT INTO henyo_words (word, category, difficulty, language, hint) VALUES
  ('Payong',        'bagay', 'easy',   'filipino', 'Panlaban sa ulan'),
  ('Relo',          'bagay', 'easy',   'filipino', 'Sinusuot sa kamay para malaman ang oras'),
  ('Telepono',      'bagay', 'easy',   'filipino', 'Gamit sa pakikipag-usap'),
  ('Upuan',         'bagay', 'easy',   'filipino', 'Uupuan mo'),
  ('Kotse',         'bagay', 'easy',   'filipino', 'Sasakyan'),
  ('Libro',         'bagay', 'easy',   'filipino', 'Binabasa'),
  ('Pinto',         'bagay', 'easy',   'filipino', 'Pasukan ng bahay'),
  ('Salamin',       'bagay', 'easy',   'filipino', 'Makikita ang sarili mo dito'),
  ('Sapatos',       'bagay', 'easy',   'filipino', 'Suotin sa paa'),
  ('Kandila',       'bagay', 'easy',   'filipino', 'Nagbibigay ng liwanag'),
  ('Gunting',       'bagay', 'easy',   'filipino', 'Gamit sa pagputol'),
  ('Bola',          'bagay', 'easy',   'filipino', 'Bilugan at panlaro'),
  ('Kutsara',       'bagay', 'easy',   'filipino', 'Gamit sa pagkain ng sopas'),
  ('Plato',         'bagay', 'easy',   'filipino', 'Lalagyan ng pagkain'),
  ('Bag',           'bagay', 'easy',   'english',  'Dala sa eskuwelahan'),
  ('Kama',          'bagay', 'easy',   'filipino', 'Hihigaan'),
  ('Mesa',          'bagay', 'easy',   'filipino', 'Lalagyan ng pagkain'),
  ('Aparador',      'bagay', 'medium', 'filipino', 'Lalagyan ng damit'),
  ('Banyo',         'bagay', 'easy',   'filipino', 'Lugar para maligo'),
  ('Eroplano',      'bagay', 'easy',   'filipino', 'Sasakyan sa hangin'),
  ('Barko',         'bagay', 'easy',   'filipino', 'Sasakyan sa dagat'),
  ('Bisikleta',     'bagay', 'easy',   'filipino', 'May dalawang gulong na sasakyan'),
  ('Pitaka',        'bagay', 'easy',   'filipino', 'Lalagyan ng pera'),
  ('Sombrero',      'bagay', 'easy',   'filipino', 'Isinusuot sa ulo'),
  ('Medyas',        'bagay', 'easy',   'filipino', 'Isinusuot sa paa bago ang sapatos'),
  ('Tsinelas',      'bagay', 'easy',   'filipino', 'Pampadali sa paa'),
  ('Langgam',       'bagay', 'easy',   'filipino', 'Maliit na hayop'),
  ('Higaan',        'bagay', 'easy',   'filipino', 'Lugar ng tulog'),
  ('Unan',          'bagay', 'easy',   'filipino', 'Lalagyan ng ulo sa tulog'),
  ('Kumot',         'bagay', 'easy',   'filipino', 'Pagtakip sa katawan sa tulog'),
  ('Bote',          'bagay', 'easy',   'filipino', 'Lalagyan ng tubig'),
  ('Pandesal',      'bagay', 'easy',   'filipino', 'Tinapay'),
  ('Kahon',         'bagay', 'easy',   'filipino', 'Parihaba na lalagyan'),
  ('Baso',          'bagay', 'easy',   'filipino', 'Lalagyan ng inumin'),
  ('Telebisyon',    'bagay', 'easy',   'filipino', 'Pinapanood ng pelikula'),
  ('Paypay',        'bagay', 'easy',   'filipino', 'Pampagpalamig ng hangin'),
  ('Yero',          'bagay', 'medium', 'filipino', 'Kisame ng bahay'),
  ('Hagdan',        'bagay', 'easy',   'filipino', 'Pababa-pataas ng bahay'),
  ('Tandang',       'bagay', 'medium', 'filipino', 'Lalaking manok'),
  ('Poso',          'bagay', 'medium', 'filipino', 'Bukal ng tubig sa lupa'),
  ('Parol',         'bagay', 'easy',   'filipino', 'Palamuti sa Pasko'),
  ('Kandado',       'bagay', 'easy',   'filipino', 'Panglock ng pinto');

-- =============================================================
-- lugar (Place) — 42 words
-- =============================================================
INSERT INTO henyo_words (word, category, difficulty, language, hint) VALUES
  ('Maynila',        'lugar', 'easy',   'filipino', 'Kabisera ng Pilipinas'),
  ('Boracay',        'lugar', 'easy',   'english',  'Sikat na beach sa Pilipinas'),
  ('Palawan',        'lugar', 'easy',   'filipino', 'Probinsya na may magandang dagat'),
  ('Cebu',           'lugar', 'easy',   'english',  'Visayas na lungsod'),
  ('Davao',          'lugar', 'easy',   'english',  'Lungsod sa Mindanao'),
  ('Baguio',         'lugar', 'easy',   'english',  'Lungsod ng ulangin'),
  ('Batangas',       'lugar', 'easy',   'english',  'Probinsya na may Taal Volcano'),
  ('Ilocos',         'lugar', 'medium', 'filipino', 'Norte na rehiyon'),
  ('Mindanao',       'lugar', 'easy',   'english',  'Pinakamalaking isla sa Pilipinas'),
  ('Quezon City',    'lugar', 'easy',   'english',  'Pinakamalaking lungsod'),
  ('Vigan',          'lugar', 'medium', 'english',  'Lumang lungsod sa Ilocos'),
  ('Chocolate Hills','lugar', 'medium', 'english',  'Tanyag sa Bohol'),
  ('Taal',           'lugar', 'medium', 'english',  'Bulkan sa loob ng lawa'),
  ('Coron',          'lugar', 'medium', 'english',  'Isla sa Palawan'),
  ('Subic',          'lugar', 'medium', 'english',  'Dating base ng Amerikano'),
  ('Pampanga',       'lugar', 'easy',   'filipino', 'Culinary capital ng Pilipinas'),
  ('Bataan',         'lugar', 'medium', 'filipino', 'Probinsya na may kasaysayan'),
  ('Cavite',         'lugar', 'easy',   'filipino', 'Probinsya malapit sa Maynila'),
  ('Rizal',          'lugar', 'easy',   'filipino', 'Probinsya sa Luzon'),
  ('Leyte',          'lugar', 'medium', 'english',  'Probinsya sa Visayas'),
  ('Samar',          'lugar', 'medium', 'english',  'Isla sa Visayas'),
  ('Zamboanga',      'lugar', 'medium', 'english',  'Lungsod sa Mindanao'),
  ('Cagayan de Oro', 'lugar', 'medium', 'english',  'Lungsod ng ginto'),
  ('Naga City',      'lugar', 'medium', 'english',  'Lungsod sa Bicol'),
  ('Iloilo',         'lugar', 'medium', 'english',  'Lungsod sa Panay'),
  ('Bacolod',        'lugar', 'medium', 'english',  'Lungsod ng ngiti'),
  ('Tagaytay',       'lugar', 'easy',   'english',  'Malamig na lungsod malapit sa Maynila'),
  ('Bulacan',        'lugar', 'easy',   'filipino', 'Probinsya ng sining'),
  ('Nueva Ecija',    'lugar', 'medium', 'english',  'Granary ng Pilipinas'),
  ('La Union',       'lugar', 'medium', 'english',  'Lugar ng surfing'),
  ('Pangasinan',     'lugar', 'medium', 'filipino', 'Probinsya ng asin'),
  ('Isabela',        'lugar', 'medium', 'english',  'Malaking probinsya sa Luzon'),
  ('Tacloban',       'lugar', 'medium', 'english',  'Kabisera ng Leyte'),
  ('General Santos', 'lugar', 'medium', 'english',  'Lungsod ng tuna'),
  ('Masbate',        'lugar', 'hard',   'filipino', 'Isla sa Bicol'),
  ('Siargao',        'lugar', 'medium', 'english',  'Surf capital ng Pilipinas'),
  ('El Nido',        'lugar', 'medium', 'english',  'Sikat na resort sa Palawan'),
  ('Intramuros',     'lugar', 'medium', 'english',  'Lumang lungsod sa Maynila'),
  ('Corregidor',     'lugar', 'hard',   'english',  'Isla sa kasaysayan'),
  ('Pinatubo',       'lugar', 'medium', 'filipino', 'Bulkan sa Luzon'),
  ('Mayon',          'lugar', 'easy',   'filipino', 'Pinakamagandang bulkan'),
  ('Apo',            'lugar', 'medium', 'filipino', 'Pinakamataas na bundok');

-- =============================================================
-- pelikula (Movie / Show) — 42 words
-- =============================================================
INSERT INTO henyo_words (word, category, difficulty, language, hint) VALUES
  ('Heneral Luna',          'pelikula', 'medium', 'filipino', 'Pelikulang pangkasaysayan'),
  ('Miracle in Cell No. 7', 'pelikula', 'easy',   'english',  'Pelikulang pampamilya'),
  ('Enteng Kabisote',       'pelikula', 'easy',   'filipino', 'Komidyang pampamilya'),
  ('Jose Rizal',            'pelikula', 'medium', 'filipino', 'Biopic ni Rizal'),
  ('Oro Plata Mata',        'pelikula', 'hard',   'filipino', 'Klasikong Filipino film'),
  ('Mano Po',               'pelikula', 'medium', 'filipino', 'Pelikulang pampamilya'),
  ('Starting Over Again',   'pelikula', 'easy',   'english',  'Romantikong pelikula'),
  ('Bonifacio',             'pelikula', 'medium', 'filipino', 'Pelikulang pangkasaysayan'),
  ('Barbie',                'pelikula', 'easy',   'english',  'Pink na pelikula'),
  ('Titanic',               'pelikula', 'easy',   'english',  'Pelikula ng barko'),
  ('Avengers',              'pelikula', 'easy',   'english',  'Marvel superhero pelikula'),
  ('Spider-Man',            'pelikula', 'easy',   'english',  'Superhero na gumagawa ng web'),
  ('Lion King',             'pelikula', 'easy',   'english',  'Pelikula ng leon'),
  ('Frozen',                'pelikula', 'easy',   'english',  'Prinsesang may kapangyarihang yelo'),
  ('Encanto',               'pelikula', 'easy',   'english',  'Disney family movie'),
  ('Ang Probinsyano',       'pelikula', 'easy',   'filipino', 'Sikat na teleserye'),
  ('FPJ''s Batang Quiapo',  'pelikula', 'easy',   'filipino', 'Teleserye ni Coco Martin'),
  ('Maalaala Mo Kaya',      'pelikula', 'medium', 'filipino', 'Sikat na drama anthology'),
  ('Forevermore',           'pelikula', 'medium', 'filipino', 'Romantikong teleserye'),
  ('It''s Showtime',        'pelikula', 'easy',   'filipino', 'Sikat na noontime show'),
  ('Eat Bulaga',            'pelikula', 'easy',   'filipino', 'Sikat na noontime show'),
  ('ASAP',                  'pelikula', 'easy',   'filipino', 'Weekend variety show'),
  ('The Hows of Us',        'pelikula', 'easy',   'english',  'Kathniel na pelikula'),
  ('Four Sisters and a Wedding','pelikula','medium','english', 'Pelikulang pampamilya'),
  ('Magnifico',             'pelikula', 'hard',   'filipino', 'Award-winning Filipino film'),
  ('Milan',                 'pelikula', 'medium', 'filipino', 'OFW themed film'),
  ('Camelot',               'pelikula', 'hard',   'english',  'Klasikong kwento'),
  ('Voltes V Legacy',       'pelikula', 'easy',   'filipino', 'Robot na teleserye'),
  ('GMA Kapuso',            'pelikula', 'easy',   'filipino', 'Sikat na network'),
  ('ABS-CBN',               'pelikula', 'easy',   'filipino', 'Sikat na network'),
  ('Pepito Manaloto',       'pelikula', 'easy',   'filipino', 'Sitcom ni Michael V'),
  ('Ang Babae sa Septic Tank','pelikula','hard',  'filipino', 'Indie Filipino film'),
  ('Bato',                  'pelikula', 'hard',   'filipino', 'Pelikula ni Bato dela Rosa'),
  ('Kita Kita',             'pelikula', 'easy',   'filipino', 'Romantikong pelikula sa Japan'),
  ('Pamilya Ko',            'pelikula', 'medium', 'filipino', 'Teleserye'),
  ('Your Name',             'pelikula', 'easy',   'english',  'Sikat na anime film'),
  ('Parasite',              'pelikula', 'medium', 'english',  'Korean Oscar-winning film'),
  ('Squid Game',            'pelikula', 'easy',   'english',  'Korean survival show'),
  ('Crash Landing on You',  'pelikula', 'easy',   'english',  'Korean romantic drama'),
  ('Hello Stranger',        'pelikula', 'easy',   'english',  'Filipino BL series'),
  ('Never Not Love You',    'pelikula', 'medium', 'english',  'Filipino romcom'),
  ('On The Job',            'pelikula', 'hard',   'english',  'Sikat na Filipino thriller');

-- =============================================================
-- kanta (Song) — 42 words
-- =============================================================
INSERT INTO henyo_words (word, category, difficulty, language, hint) VALUES
  ('Ang Huling El Bimbo',   'kanta', 'medium', 'filipino', 'Eraserheads na kanta'),
  ('Pag-ibig',              'kanta', 'easy',   'filipino', 'Sikat na OPM'),
  ('Harana',                'kanta', 'easy',   'filipino', 'Pagserenade'),
  ('Dahil Sa Iyo',          'kanta', 'medium', 'filipino', 'Sikat na kundiman'),
  ('Bayan Ko',              'kanta', 'medium', 'filipino', 'Awit ng bansa ni Freddie Aguilar'),
  ('Lupang Hinirang',       'kanta', 'easy',   'filipino', 'Pambansang awit ng Pilipinas'),
  ('Ikaw',                  'kanta', 'easy',   'filipino', 'Yano na kanta'),
  ('Narda',                 'kanta', 'medium', 'filipino', 'Kamikazee na kanta'),
  ('Parokya ni Edgar',      'kanta', 'medium', 'filipino', 'Band na sikat sa OPM'),
  ('Sana Maulit Muli',      'kanta', 'easy',   'filipino', 'Regine Velasquez na kanta'),
  ('Umagang Kay Ganda',     'kanta', 'easy',   'filipino', 'Good morning song'),
  ('Kundiman',              'kanta', 'medium', 'filipino', 'Tradisyunal na awit ng pag-ibig'),
  ('Alapaap',               'kanta', 'medium', 'filipino', 'Eraserheads na kanta'),
  ('Kailangan Kita',        'kanta', 'medium', 'filipino', 'Sikat na love song'),
  ('Hanggang',              'kanta', 'easy',   'filipino', 'Sikat na OPM ballad'),
  ('Mundo',                 'kanta', 'easy',   'filipino', 'IV of Spades na kanta'),
  ('Pare Ko',               'kanta', 'easy',   'filipino', 'Eraserheads na kanta'),
  ('Kathang Isip',          'kanta', 'easy',   'filipino', 'Ben&Ben na kanta'),
  ('Di Na Muli',            'kanta', 'medium', 'filipino', 'Parokya na kanta'),
  ('Tayong Dalawa',         'kanta', 'easy',   'filipino', 'Sikat na love song'),
  ('Habang Buhay',          'kanta', 'easy',   'filipino', 'Sikat na wedding song'),
  ('Miss Kita Kung Christmas','kanta','easy',  'filipino', 'Paskong kanta'),
  ('Pasko Na',              'kanta', 'easy',   'filipino', 'Paskong kanta'),
  ('Ang Buhay Natin',       'kanta', 'medium', 'filipino', 'Couple song'),
  ('Multo',                 'kanta', 'easy',   'filipino', 'Cup of Joe na kanta'),
  ('Kahit Ayaw Mo Na',      'kanta', 'easy',   'filipino', 'This Band na kanta'),
  ('Probinsyana',           'kanta', 'easy',   'filipino', 'Sikat na kanta'),
  ('Jingle Bells',          'kanta', 'easy',   'english',  'Sikat na Christmas song'),
  ('Happy Birthday',        'kanta', 'easy',   'english',  'Awit sa kaarawan'),
  ('We Are The World',      'kanta', 'medium', 'english',  'Classic charity song'),
  ('Bohemian Rhapsody',     'kanta', 'medium', 'english',  'Queen na kanta'),
  ('Shape of You',          'kanta', 'easy',   'english',  'Ed Sheeran na kanta'),
  ('Butter',                'kanta', 'easy',   'english',  'BTS na kanta'),
  ('Dynamite',              'kanta', 'easy',   'english',  'BTS na kanta'),
  ('DITTO',                 'kanta', 'medium', 'english',  'NewJeans na kanta'),
  ('Easy',                  'kanta', 'medium', 'english',  'Le Sserafim na kanta'),
  ('Malayo',                'kanta', 'medium', 'filipino', 'SB19 na kanta'),
  ('GENTO',                 'kanta', 'medium', 'filipino', 'SB19 na kanta'),
  ('Na Na Na',              'kanta', 'medium', 'filipino', 'BINI na kanta'),
  ('Pantropiko',            'kanta', 'easy',   'filipino', 'BINI na kanta'),
  ('Paubaya',               'kanta', 'easy',   'filipino', 'Moira Dela Torre na kanta'),
  ('Ikaw at Ako',           'kanta', 'easy',   'filipino', 'Sikat na love song');

-- =============================================================
-- palaro (Sport / Game) — 42 words
-- =============================================================
INSERT INTO henyo_words (word, category, difficulty, language, hint) VALUES
  ('Piko',             'palaro', 'easy',   'filipino', 'Tradisyunal na laruan'),
  ('Patintero',        'palaro', 'easy',   'filipino', 'Laruan sa daan'),
  ('Luksong Baka',     'palaro', 'easy',   'filipino', 'Tradisyunal na laro'),
  ('Tumbang Preso',    'palaro', 'easy',   'filipino', 'Tradisyunal na laro'),
  ('Sipa',             'palaro', 'easy',   'filipino', 'Pambansang laro ng Pilipinas'),
  ('Agawan Base',      'palaro', 'easy',   'filipino', 'Tradisyunal na laro'),
  ('Basketball',       'palaro', 'easy',   'english',  'Sikat na sports sa Pilipinas'),
  ('Volleyball',       'palaro', 'easy',   'english',  'Sports na may net'),
  ('Billiards',        'palaro', 'easy',   'english',  'Sports na may mesa'),
  ('Boxing',           'palaro', 'easy',   'english',  'Sports ni Pacquiao'),
  ('Sepak Takraw',     'palaro', 'medium', 'english',  'Sepak sports ng Pilipinas'),
  ('Arnis',            'palaro', 'medium', 'filipino', 'Pambansang martial arts'),
  ('Chess',            'palaro', 'easy',   'english',  'Board game na estratehiya'),
  ('Scrabble',         'palaro', 'easy',   'english',  'Word board game'),
  ('Bahay-Bahayan',    'palaro', 'easy',   'filipino', 'Laruan ng mga bata'),
  ('Taguan',           'palaro', 'easy',   'filipino', 'Hide and seek'),
  ('Kudlit-kudlitan',  'palaro', 'medium', 'filipino', 'Tradisyunal na laro'),
  ('Mahjong',          'palaro', 'easy',   'english',  'Chinese tile game'),
  ('Pusoy',            'palaro', 'easy',   'filipino', 'Card game'),
  ('Tongits',          'palaro', 'easy',   'filipino', 'Sikat na card game'),
  ('Sungka',           'palaro', 'medium', 'filipino', 'Tradisyunal na board game'),
  ('Badminton',        'palaro', 'easy',   'english',  'Sports na may shuttlecock'),
  ('Tennis',           'palaro', 'easy',   'english',  'Sports na may raket'),
  ('Swimming',         'palaro', 'easy',   'english',  'Sports sa tubig'),
  ('Football',         'palaro', 'easy',   'english',  'Sports na may bola at gol'),
  ('Baseball',         'palaro', 'medium', 'english',  'Sports na may bat at bola'),
  ('Softball',         'palaro', 'medium', 'english',  'Katulad ng baseball'),
  ('Track and Field',  'palaro', 'easy',   'english',  'Tumakbo at lumukso'),
  ('Gymnastics',       'palaro', 'medium', 'english',  'Akrobatikong sports'),
  ('Taekwondo',        'palaro', 'medium', 'english',  'Korean martial arts'),
  ('Judo',             'palaro', 'medium', 'english',  'Japanese martial arts'),
  ('Karate',           'palaro', 'easy',   'english',  'Japanese martial arts'),
  ('Wrestling',        'palaro', 'easy',   'english',  'Sports na pagbabagsak'),
  ('Golf',             'palaro', 'easy',   'english',  'Sports na may golf club'),
  ('Darts',            'palaro', 'easy',   'english',  'Palaro ng tumpak na paghagis'),
  ('Bowling',          'palaro', 'easy',   'english',  'Palaro ng bowling ball at pins'),
  ('Jackstone',        'palaro', 'easy',   'filipino', 'Laruan ng mga bata'),
  ('Trumpo',           'palaro', 'medium', 'filipino', 'Tradisyunal na laruan'),
  ('Saranggola',       'palaro', 'easy',   'filipino', 'Laruan na lipad'),
  ('Palo Sebo',        'palaro', 'medium', 'filipino', 'Tradisyunal na palaruan'),
  ('Luksong Tinik',    'palaro', 'easy',   'filipino', 'Tradisyunal na laro'),
  ('Buwan ng Buwan',   'palaro', 'medium', 'filipino', 'Tradisyunal na laro');
